// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const PageTranslator: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/page-translator')['PageTranslator']
  const ProgressUI: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/progress-ui')['ProgressUI']
  const browser: typeof import('wxt/browser')['browser']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const extractTextBlocks: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/dom-parser')['extractTextBlocks']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getSettings: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/settings')['getSettings']
  const hasTranslations: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/renderer')['hasTranslations']
  const injectScript: typeof import('wxt/client')['injectScript']
  const removeAllTranslations: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/renderer')['removeAllTranslations']
  const renderBatchTranslations: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/renderer')['renderBatchTranslations']
  const renderTranslation: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/renderer')['renderTranslation']
  const saveSettings: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/settings')['saveSettings']
  const segmentIntoBatches: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/segmenter')['segmentIntoBatches']
  const setDisplayMode: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/renderer')['setDisplayMode']
  const storage: typeof import('wxt/storage')['storage']
  const translateBatch: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/api')['translateBatch']
  const translateText: typeof import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/api')['translateText']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { TranslateParams, TranslateBatchParams, TranslateApiResult } from 'D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/api'
  import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/api')
  // @ts-ignore
  export type { TextBlock } from 'D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/dom-parser'
  import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/dom-parser')
  // @ts-ignore
  export type { PageTranslator, PageTranslateState } from 'D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/page-translator'
  import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/page-translator')
  // @ts-ignore
  export type { ProgressUI, ProgressState, ProgressInfo } from 'D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/progress-ui'
  import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/progress-ui')
  // @ts-ignore
  export type { TranslateBatch } from 'D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/segmenter'
  import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/segmenter')
  // @ts-ignore
  export type { DisplayMode, ExtensionSettings } from 'D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/settings'
  import('D:/WorkingSet/PythonProjects/深水工作/Tom_TranslateApp/packages/extension/utils/settings')
}
